### PR TITLE
Enhancement: Update php cs fixer version

### PR DESCRIPTION
**Pull request by mklbravo**
This pull request

- [x] Update `php-cs-fixer` to version `~3.22.0`
- [x] Fix `- Rule "no_trailing_comma_in_list_call" is deprecated. Use "no_trailing_comma_in_singleline" instead.`
- [x] Fix: `- Rule "no_trailing_comma_in_singleline_array" is deprecated. Use "no_trailing_comma_in_singleline" instead.`
- [x] Fix: `- Rule "single_space_after_construct" is deprecated. Use "single_space_around_construct" instead.`
- [x] Fix: `- Rule "single_blank_line_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.`
- [x] Fix: `- Rule "no_blank_lines_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead`
- [x] Fix: `- Rule "function_typehint_space" is deprecated. Use "type_declaration_spaces" instead.`
- [x] Fix: `- Rule "braces" is deprecated. Use "single_space_around_construct", "control_structure_braces", "control_structure_continuation_position", "declare_parentheses", "no_multiple_statements_per_line", "curly_braces_position", "statement_indentation" and "no_extra_blank_lines" instead.`
- [x] configure all non-deprecated fixers

### CODE REVIEW

**Comment by alexmart** [comment]
@krwi @mklbravo I got a notification on this one so I checked it out. I think it's a good addition to complete/merge, no?

**Comment by krwi** [comment]
> @krwi @mklbravo I got a notification on this one so I checked it out. I think it's a good addition to complete/merge, no?

What's the state of this, is it abandoned? The stale notification came for a reason.

**Comment by mklbravo** [comment]
completely forgot about this, maybe I can give it another try :)

**Comment by krwi** [comment]
@mklbravo does it make sense to reopen this in the next refactoring sprint?

**Pull request closed without merging**
